taiyoh/sqsd

- Gopkg.lock
- backoff.go
- queue_tracker.go
via: https://www.slideshare.net/lestrrat/goapi-go-conference-2018-spring
> changed exponential backoff library for simplicty.

- message_consumer_test.go
- queue_tracker.go
I received some advices before, but not implemented.
In this PR, I correspond to these advices.
> respond to some advices

- cmd/sqsd/main.go
- logger.go
- message_consumer.go
- message_consumer_test.go
- message_producer.go
- message_producer_test.go
- queue_tracker.go
- queue_tracker_export_test.go
- queue_tracker_test.go
- resource.go
- stat_handler.go
- stat_handler_test.go
Each struct fields in sqsd are carelessly public.
So, let some struct fields which is no need for publish hide from outer package.
> make many struct fields private

- conf_test.go
- message_consumer_test.go
- message_producer_test.go
- mock_for_test.go
- queue_test.go
- queue_tracker_test.go
- resource_test.go
- stat_handler.go
- stat_handler_test.go
> let test files settle in sqsd_test package

- backoff.go
- go.mod
- go.sum
simplify backoff implementation for healthcheck
> remove backoff module

- docker/Dockerfile
> use multistage build for Dockerfile

- message_consumer.go
- message_consumer_test.go
- producer_consumer.go
- queue.go
via https://travis-ci.org/github/taiyoh/sqsd/builds/662270814
> CI detected race condition

- actor/consumer.go
- actor/gateway.go
- actor/gateway_test.go
- actor/logger.go
- cmd/dummyhttpd/main.go
- cmd/sqsd-actor/main.go
> add debug logging

- actor/consumer.go
- actor/gateway.go
- actor/gateway_test.go
- cmd/sqsd-actor/main.go
- go.mod
- go.sum
- read envfile
- stop actor by myself
> signal handling and closing

- .gitignore
- actor/consumer.go
- actor/consumer_test.go
- actor/gateway.go
- actor/gateway_test.go
- actor/invoker.go
- actor/invoker_test.go
- actor/monitoring_service.go
- actor/queue.go
- cmd/sqsd-actor/main.go
> rewrite consumer

- .github/workflows/ci.yml
ref: https://github.com/taiyoh/sqsd/pull/131
oops
> fix: add cache for user's ci

- actor/monitoring_service.go
- actor/monitoring_service_test.go
test coverage is lacked to release new version.
> fix(test): add MonitoringService behavior

- actor/grpc_test.go
- actor/system_test.go
> fix(test): add gRPC server handling test

- gateway.go
- locker/locker.go
- locker/memory/locker.go
- locker/memory/locker_test.go
- locker/noop/locker.go
`QueueLocker` is not core feature for sqsd, so I want to separate it from main package.
Set locker package and moved codes about locker's functions.
> feat: add locker interface from new package

- locker/locker.go
- locker/memory/locker.go
- locker/memory/locker_test.go
these definitions are common settings for locker, so set these on locker package.
> expire duration and RunQueueLocker set on locker

- go.mod
- go.sum
- github.com/AsinkronIT/protoactor-go
- github.com/aws/aws-sdk-go
- google.golang.org/grpc
> chore: bump dependencies

- README.md
- cmd/dummyhttpd/main.go
- cmd/sqsd/main.go
- cmd/sqsd/main_test.go
- locker/memory/locker.go
- locker/memory/locker_test.go
sqsd binary can select Redis or Memory locker.
> add locker to sqsd binary

- gateway.go
This change enables to edit MaxNumberOfMessages of SQS recieving messages request.
Default value is 10, but using FetcherMaxMessages can change it between 1 and 10.
> feat(fetcher): :wheelchair: enable to set MaxNumberOfMessages

- aws_setup_test.go
- cmd/sqsd/main.go
- containers/elasticmq/app.conf
- docker-compose.yml
- gateway.go
- gateway_test.go
add `sqsd.FetcherWaitTime` to set `WaitTimeSeconds` for receiving message from SQS queue
> refactor(fetcher): make wait time controllable

- consumer.go
- consumer_test.go
- gateway_test.go
- grpc_test.go
- monitoring_service_test.go
- system.go
and organize worker definition
> refactor(consumer): remove consumer
